# Generated by Django 3.1.3 on 2020-11-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'verbose_name': 'Account category', 'verbose_name_plural': 'Account categories'},
        ),
        migrations.AlterModelOptions(
            name='accountlanguage',
            options={'verbose_name': 'Account language', 'verbose_name_plural': 'Account languages'},
        ),
        migrations.AlterModelOptions(
            name='ageinterval',
            options={'verbose_name': 'Age interval', 'verbose_name_plural': 'Age intervals'},
        ),
        migrations.AlterModelOptions(
            name='audienceage',
            options={'verbose_name': 'Audience age', 'verbose_name_plural': 'Audience ages'},
        ),
        migrations.AlterModelOptions(
            name='audiencecity',
            options={'verbose_name': 'Audience city', 'verbose_name_plural': 'Audience cities'},
        ),
        migrations.AlterModelOptions(
            name='audiencecountry',
            options={'verbose_name': 'Audience country', 'verbose_name_plural': 'Audience countries'},
        ),
        migrations.AlterModelOptions(
            name='audiencegender',
            options={'verbose_name': 'Audience gender', 'verbose_name_plural': 'Audience genders'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='gendertype',
            options={'verbose_name': 'Gender type', 'verbose_name_plural': 'Gender types'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': 'Interval', 'verbose_name_plural': 'Intervals'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_quality_score',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
