# Generated by Django 3.1.3 on 2020-11-05 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20201105_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraping.category', to_field='hype_id'),
        ),
    ]
