# Generated by Django 3.1.3 on 2020-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20201105_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='quality_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
